### ISSUE TITLE
Invalid project layout

### ISSUE THREAD

**Issue by nephest** [NeWHoriZonS69/UFL-Website#24]
It seems like gradle config or project layout is invalid. I'm not sure since I have no experience with gradle, but here are my problems:
* the root `settings.gradle` file has space in it's name, so it's skipped by gradle
* the source layout is invalid, the `java` directory is skipped. current path `/src/main` should be changed to `/src/main/java`
* missing `build.gradle` for subprojects?

**Comment by axillusion** [comment]
Fixed on my last commit, everything should be added by now
